// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWhLo5pNzvHpbq3n5I03vuMvWKOQbCBiw',
    appId: '1:342531321322:web:83bd65b317b5f8140ad693',
    messagingSenderId: '342531321322',
    projectId: 'metodologias-1b088',
    authDomain: 'metodologias-1b088.firebaseapp.com',
    storageBucket: 'metodologias-1b088.firebasestorage.app',
    measurementId: 'G-MJSC36ZCPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92ygRIe4hKgX5WS7NxwKxZJWYruIdEz8',
    appId: '1:342531321322:android:98cfa22882fa1b640ad693',
    messagingSenderId: '342531321322',
    projectId: 'metodologias-1b088',
    storageBucket: 'metodologias-1b088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi-EXbYlPtb85Hjq5StZ8wN5IzhLk7_Cs',
    appId: '1:342531321322:ios:eaa39b7eff17bf0a0ad693',
    messagingSenderId: '342531321322',
    projectId: 'metodologias-1b088',
    storageBucket: 'metodologias-1b088.firebasestorage.app',
    iosBundleId: 'com.stocknet.stocknet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi-EXbYlPtb85Hjq5StZ8wN5IzhLk7_Cs',
    appId: '1:342531321322:ios:8defa033c3b71ff90ad693',
    messagingSenderId: '342531321322',
    projectId: 'metodologias-1b088',
    storageBucket: 'metodologias-1b088.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWhLo5pNzvHpbq3n5I03vuMvWKOQbCBiw',
    appId: '1:342531321322:web:675259a3e876b8e40ad693',
    messagingSenderId: '342531321322',
    projectId: 'metodologias-1b088',
    authDomain: 'metodologias-1b088.firebaseapp.com',
    storageBucket: 'metodologias-1b088.firebasestorage.app',
    measurementId: 'G-5DBZXCN73V',
  );
}
